FROM rockylinux/rockylinux:8-minimal

RUN set -eux \
    && microdnf update --nodocs \
    && microdnf module enable python39 \
    && microdnf install --nodocs -y epel-release \
    && microdnf install --nodocs --enablerepo=powertools -y java-17-openjdk-headless git python3.11 python3.11-pip podman-docker jq bind-utils netcat openssh unzip rsync

ARG TARGETPLATFORM
RUN set -eux \
    && export VAULT_VERSION=$(curl -L -sS -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/hashicorp/vault/releases/latest | jq -r '.tag_name' | sed 's#^v##') \
    && export VAULT_PLATFORM=$(echo ${TARGETPLATFORM} | sed 's#/#_#') \
    && curl -sS -L -o /tmp/vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_${VAULT_PLATFORM}.zip \
    && unzip -d /usr/bin /tmp/vault.zip vault \
    && rm -f /tmp/vault.zip

RUN set -eux \
    && pip3.11 install --no-cache virtualenv yq
