FROM rockylinux/rockylinux:10-minimal

RUN set -eux \
    && microdnf --nodocs -y update \
    && microdnf --nodocs -y install epel-release \
    && microdnf --nodocs --enablerepo=crb -y install java-21-openjdk-headless git python3.12 python3.12-pip podman-docker jq bind-utils netcat nmap openssh unzip rsync

ARG TARGETPLATFORM
RUN set -eux \
    && export VAULT_VERSION=$(curl -L -sS -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/hashicorp/vault/releases/latest | jq -r '.tag_name' | sed 's#^v##') \
    && export VAULT_PLATFORM=$(echo ${TARGETPLATFORM} | sed 's#/#_#') \
    && curl -sS -L -o /tmp/vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_${VAULT_PLATFORM}.zip \
    && unzip -d /usr/bin /tmp/vault.zip vault \
    && rm -f /tmp/vault.zip

RUN set -eux \
    && pip3.12 install --no-cache virtualenv yq
