FROM rockylinux:9-minimal

RUN set -eux \
	&& microdnf --nodocs -y update \
	&& microdnf --nodocs -y install epel-release

RUN set -eux \
	&& curl -sS -L -o /etc/yum.repos.d/vault.repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

RUN set -eux \
	&& microdnf --nodocs --enablerepo=crb -y install java-17-openjdk-headless git python3.11 python3.11-pip podman-docker jq bind-utils netcat nmap vault

RUN set -eux \
	&& pip3.11 install --no-cache virtualenv yq
