FROM alpine:3.21

RUN set -eux \
    && apk upgrade --no-cache \
    && apk add --no-cache \
        jq \
        git \
        bash \
        curl \
        nmap \
        unzip \
        gcompat \
        openssh \
        python3 \
        py3-pip \
        yq-python \
        alpine-sdk \
        build-base \
        python3-dev \
        py3-virtualenv \
        netcat-openbsd \
        lsb-release-minimal \
        openjdk17-jre-headless
