FROM ghcr.io/esphome/esphome:2026.5.2


RUN set -eux \
    && apt-get update \
    && apt-get install -y \
        jq \
        git \
        bash \
        curl \
        nmap \
        unzip \
        openjdk-21-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ ]
CMD []
