FROM rockylinux:9-minimal

RUN set -eux \
	&& microdnf --nodocs -y update \
	&& microdnf --nodocs -y install epel-release

RUN set -eux \
	&& microdnf --nodocs --enablerepo=crb -y install java-17-openjdk-headless git python3.11 python3.11-pip podman-docker jq bind-utils netcat nmap

RUN set -eux \
	&& pip3.11 install --no-cache virtualenv yq
